// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4GpOd9yBeWv2q-KxKfLHMoyd9nu7xDg',
    appId: '1:416539480007:android:e48c246f5815778083d3e2',
    messagingSenderId: '416539480007',
    projectId: 'shoppingapp-7acb3',
    storageBucket: 'shoppingapp-7acb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLjpXuLEnotOUOcqHBLFwdHCaKChy-C1A',
    appId: '1:416539480007:ios:3f5a7bb3f78487b883d3e2',
    messagingSenderId: '416539480007',
    projectId: 'shoppingapp-7acb3',
    storageBucket: 'shoppingapp-7acb3.firebasestorage.app',
    androidClientId: '416539480007-s5ai7dviuj5s91em96d5m5jq984j1oph.apps.googleusercontent.com',
    iosClientId: '416539480007-o8paugvd85qdbqn5e3e64mocqt5mug3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}